### ISSUE TITLE
Doc Request: Creating / writing spec files 

### ISSUE THREAD

**Issue by DevLab2425** [ProjectEvergreen/www.greenwoodjs.dev#110]
## Summary

When creating the spec file for the edit-on-github component, it was a bit unclear what was boostrapping for the tests, and what was specific to the file-at-test. 

## Details

The use of the mock graph and adding the custom element to the DOM wasn't immediately clear and it was a bit. of a struggle getting a new spec file up and running from scratch. Partially due to my assumption of how it might work, and how it _actually_ works. :smile: , but nevertheless, when I went looking for some details, [the CONTRIBUTING.md didn't include many details](https://github.com/ProjectEvergreen/www.greenwoodjs.dev/blob/main/CONTRIBUTING.md#testing) on the specifics. 

### Proposed outline

- File setup
    - Imports
    - Constant / global value setup 
    - Simple describe / it example (maybe not?)
- Default test setup (`before()`)
- Variant changes

I'm happy to document what I've done and getting something started. 

EDIT: correct url link to file

**Comment by thescientist13** [comment]
Hey @DevLab2425 , good call out here.  I spent all my time documenting it for our guides content, but completely overlooking linking out to it from the contributing docs!  🤦 

See for reference:
- [_/guides/ecosystem/storybook/_](https://super-tapioca-5987ce.netlify.app/guides/ecosystem/storybook/)
- [_/guides/ecosystem/web-test-runner/_](https://super-tapioca-5987ce.netlify.app/guides/ecosystem/web-test-runner/)


I think those should help add all that missing context, at least around the content as data stuff, and so if we just wanted to add a callout in our contributing docs, I think that would definitely be a helpful PR.  🙌

**Comment by thescientist13** [comment]
That said, the website docs shouldn't need to get too deep into testing _practices / preferences_ , as it should stay focused on the actual setup / integration IMO.  So if you did want to capture any _project_ specific testing conventions, then I am fine to put those in the contributing docs (including links to Greenwood integration docs).  👍
