### ISSUE TITLE
Blog Landing Page

### ISSUE THREAD

**Issue by thescientist13** [ProjectEvergreen/www.greenwoodjs.dev#34]
## Summary

Create the Blog Landing page according to the designs and also incorporate all the needed information architecture changes.

![Screenshot 2024-06-03 at 4 20 28 PM](https://github.com/ProjectEvergreen/www.greenwoodjs.dev/assets/895923/2a134fdf-7dc2-425e-b291-65fa89862139)

## Details
1. [x] Will need a _src/pages/blog/index.html_ file
1. [ ] (nice to have) filter / sort posts, like based on tags (news, technical, op-ed, etc)
1. [ ] Lighthouse / A11y check

----

## Open Items
1. [x] Need a canonical Figma file link / screenshot reference
1. [x] Understand needs around using https://github.com/ProjectEvergreen/greenwood/issues/1167
1. [ ] This could be a good first issue

**Comment by Auhseh** [comment]
I just contributed.

I tried using open-props, but it doesn’t seem to cover all the sizes and specs in the design.

E.g There are specific sizing and spacing in the design that open-props don’t cover.

The images in the blog design are dummy placeholders and will be replaced by the actual content when the site is ready

**Comment by thescientist13** [comment]
@Auhseh 
Can you please start a thread in https://github.com/ProjectEvergreen/www.greenwoodjs.dev/discussions/7 with examples of what you mean?

**Comment by thescientist13** [comment]
Just noticed the email / newsletter CTA, and so probably won't be including that in the initial version, nor do I think I would be that interested in maintaining a mailing list in general.
