### ISSUE TITLE
social icons in header breaking out of the container on lower breakpoints

### ISSUE THREAD

**Issue by thescientist13** [ProjectEvergreen/www.greenwoodjs.dev#55]
## Summary
Noticed that the little grouping of social icons overflows outside of the header container on smaller breakpoints.
 
![Screenshot 2024-06-05 at 8 46 52 AM](https://github.com/ProjectEvergreen/www.greenwoodjs.dev/assets/895923/96ca8750-4c03-4569-be7a-cbd80787e914)

## Details
Seems to be an padding issue?  The left side  seems to be pushing things over more than they need to be at a certain breakpoint, where as normally everything is nicely centered
![Screenshot 2024-06-05 at 8 50 01 AM](https://github.com/ProjectEvergreen/www.greenwoodjs.dev/assets/895923/3dfc9c59-6eb0-4824-9c74-93f52f416497)

**Comment by rabelmervin** [comment]
Hi sir @thescientist13 , I'm interested in working in this issue. Could you provide me the location of the code ???

**Comment by thescientist13** [comment]
Hey @rabelmervin , thanks for jumping in!

All the header code / styles can be found here.
https://github.com/ProjectEvergreen/www.greenwoodjs.dev/tree/main/src/components/header

**Comment by rabelmervin** [comment]
Hi sir @thescientist13, html file for the given issue is missing in header . Can't able to run or test the modifications. Could you please provide it or Should I need to create that tooo ???

**Comment by thescientist13** [comment]
Hey @rabelmervin , the project comes with Storybook installed, so you should be able to use that to test components in isolation, and which should support reproducing / fixing this bug
https://github.com/ProjectEvergreen/www.greenwoodjs.dev?tab=readme-ov-file#storybook
![Screenshot 2024-06-07 at 11 02 14 AM](https://github.com/ProjectEvergreen/www.greenwoodjs.dev/assets/895923/0f54da70-2d68-4426-85bb-34ebc0f7e679)

**Comment by thescientist13** [comment]
I can't seem to reproduce this, I think it may have been resolved as part of #47
