### ISSUE TITLE
Twitter / X icon is not vertically aligned with other icons

### ISSUE THREAD

**Issue by thescientist13** [ProjectEvergreen/www.greenwoodjs.dev#66]
## Summary

In the header and footer components, the social icon for Twitter / X does not seem to be vertically aligned with the other two icons

![Screenshot 2024-06-30 at 2 25 08 PM](https://github.com/ProjectEvergreen/www.greenwoodjs.dev/assets/895923/b204dc37-f83f-4785-9e26-9975fc492170)
![Screenshot 2024-06-30 at 2 25 20 PM](https://github.com/ProjectEvergreen/www.greenwoodjs.dev/assets/895923/d610164a-551c-41b9-8bf7-243819e7ef5f)

## Details

Would be good to go into each of these components and the tweak the styles
- https://github.com/ProjectEvergreen/www.greenwoodjs.dev/tree/main/src/components/footer
- https://github.com/ProjectEvergreen/www.greenwoodjs.dev/tree/main/src/components/header

----

Maybe a good opportunity to do at the same time #63 ?

**Comment by lpapanik** [comment]
I have created a pull request that may solve this issue.

https://github.com/ProjectEvergreen/www.greenwoodjs.dev/pull/67
