### ISSUE TITLE
clicking the greenwood logo in the header should link to the home page

### ISSUE THREAD

**Issue by thescientist13** [ProjectEvergreen/www.greenwoodjs.dev#68]
## Summary

Currently the headers has links for all pages, but no easy way to get back to the home page.

![Screenshot 2024-07-06 at 2 26 02 PM](https://github.com/ProjectEvergreen/www.greenwoodjs.dev/assets/895923/406d305c-21bd-4a07-ab65-8a2652aa3a1e)

Typically, pages with a header logo usually link back to the home page when clicked on them, so we should enable that as well.

## Details
Should be pretty simple, just need to wrap [the logo with an `<a>` tag](https://github.com/ProjectEvergreen/www.greenwoodjs.dev/blob/main/src/components/header/header.js#L20), and probably should add a test case for that.

**Comment by umavl6** [comment]
@thescientist13 I will work on this.

**Comment by thescientist13** [comment]
Thanks @umavl6 !
